### ISSUE TITLE
*_arc.txt files missing in data

### ISSUE THREAD

**Issue by blondegeek** [Danie1Johnson/research#14]
Could you please upload the *_arc.txt files (in the data/ folder) used by get_bg_ss in bga_4_0.py. Thanks!

**Comment by Danie1Johnson** [comment]
I just added the 5 _arc files for the Platonic solids.I originally did not include these files as they can get arbitrarily large. Basically on the order of V + E lines for V vertices and E edges in the state space graph. You can generate _arc files for any of the polyhedra here by running the building_game_5_1 binary with the polyhedron file as a command line argument (see below for icosahedron example). That binary will give output as below, I think the columns are (1) # faces in inermediate (2) # intermediates (3) # shellable intermediates (4) # edges in graph between f and f-1 faced intermediates (5) same but for the shellable subgraph (6) compute time in seconds. The corresponding _arc and _log files will also be written. 

If you're interested, input files for polyhedra I haven't covered can be made, but due to the 'combinatorial exploion' anything much past 30 faces becomes intractable in temrs of both the compute time and storage required. 

```
daniel@turing:~/research/data$ ./building_game_5_1 icosahedron_5_1.txt 
0	1	1
1	1	1	1	1	0
2	1	1	1	1	0
3	1	1	1	1	0
4	4	4	4	4	0
5	6	6	13	13	0
6	14	14	30	30	0
7	26	25	74	72	0
8	58	51	173	154	0
9	109	76	389	285	0
10	225	110	851	432	0
11	359	76	1670	432	0
12	532	51	2802	285	0
13	549	25	3761	154	0
14	433	14	3668	72	0
15	214	6	2408	30	0
16	89	4	1044	13	0
17	20	1	295	4	0
18	6	1	50	1	0
19	1	1	6	1	0
20	1	1	1	1	0
Vertices: 	2650	470
Edges:    	17242	1986
Pathways: 	57396146640	105999738
Rotations:	60
Time:     	0
daniel@turing:~/research/data$ 
```

**Comment by blondegeek** [comment]
Thanks very much!
